/* /*
 * This source file was generated by the Gradle 'init' task
 */
package parcial;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {

        Scanner sc = new Scanner(System.in);
        int flota = 0;
        int metrosCarro;
        float gasolinaCarro, kilometrosCarro;
        float gasolinaGeneral = 0;
        String valorInvalido = "[VALOR INVALIDO]";

        while (flota != -1) {
            System.out.println("-------COMSUMO GASOLINA FLOTA---------");
            System.out.println("Ingrese la cantidad de carros en la flota (-1 para salir): ");
            flota = sc.nextInt();
            if (flota > 0) {
                for (int i = 1; i <= flota; i++) {
                    gasolinaCarro = 0;
                    kilometrosCarro = 0;
                    metrosCarro = 0;
                    do {
                        System.out.println("----- Vehiculo " + i + "-----");
                        System.out.println("Ingrese los metros recorridos por el vehiculo " + i + ": ");
                        metrosCarro = sc.nextInt();
                        if (metrosCarro < 0) {
                            System.out.println(valorInvalido);
                        } else {
                            kilometrosCarro = metrosCarro / 1000;
                            gasolinaCarro = calcularConsumoGasolina(kilometrosCarro);
                            System.out.println("[ KM Recorridos: " + kilometrosCarro + " ]  "
                                    + "  [ Litros de Gasolina: " + gasolinaCarro + " ]");
                            System.out.println("");
                            gasolinaGeneral += gasolinaCarro;

                        }
                    } while (metrosCarro < 0);
                }
                System.out.println("");
                System.out.println("===========  TOTAL GASOLINA FLOTA DE " + flota + " VEHICULOS ============");
                System.out.println("[  " + gasolinaGeneral + " Litros  ]");
                System.out.println("");
                System.out.println("");
                System.out.println("");

            } else if (flota == -1) {
                System.out.println("Saliendo del programa...");
            } else {
                System.out.println(valorInvalido);
            }
        }

    }

    /*
     * Implemente una funcion llamada calcularConsumoGasolina que cumpla con las
     * siguientes caracteristicas
     * Recibe:
     * - Un float representando los km recorridos
     * Retorna:
     * - Un float representando los litros de gasolina consumidos
     */
    // ------------------------------------------------------------------
    // Implemente la funcion en este espacio
    public static float calcularConsumoGasolina(float kmRecorrido) {
        try {
            if (kmRecorrido >= 0) {
                return ((kmRecorrido * 55) / 750);
            } else {
                return -1;
            }
        } catch (Exception e) {
            return -1;
        }

    }
    // ------------------------------------------------------------------

}
